services:
  textgrab:
    image: ghcr.io/therepos/textgrab:latest
    container_name: textgrab
    ports:
      - "8000:8000"
    volumes:
      - textgrab-data:/data/models
    restart: unless-stopped
    pull_policy: always

volumes:
  textgrab-data:
